/*
 * QuickStart DataHub API
 * This is a sample of a QuickStart DataHub Swagger doucment defining endpoints to be mocked
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.marklogic.hub.client.api;

import com.marklogic.hub.client.model.Flow;
import com.marklogic.hub.client.model.Step;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FlowsApi
 */
@Ignore
public class FlowsApiTest {

    private final FlowsApi api = new FlowsApi();

    
    /**
     * Create flow
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createFlowTest() {
        Flow body = null;
        Flow response = api.createFlow(body);

        // TODO: test validations
    }
    
    /**
     * Delete flow by Id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteFlowTest() {
        String flowId = null;
        api.deleteFlow(flowId);

        // TODO: test validations
    }
    
    /**
     * Find flow by Id
     *
     * ....
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFlowTest() {
        String flowId = null;
        Flow response = api.getFlow(flowId);

        // TODO: test validations
    }
    
    /**
     * Returns all flows
     *
     * Returns all flows
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFlowsTest() {
        List<Flow> response = api.getFlows();

        // TODO: test validations
    }
    
    /**
     * Run a Flow
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void runFlowTest() {
        String flowId = null;
        Step response = api.runFlow(flowId);

        // TODO: test validations
    }
    
    /**
     * Update flow by Id
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateFlowTest() {
        String flowId = null;
        Flow body = null;
        api.updateFlow(flowId, body);

        // TODO: test validations
    }
    
}
